---
#
# Ansible managed
#
repository:
  description: Ansible Role for Atlassian Bitbucket Installation
  homepage: https://buluma.github.io/
  topics: bitbucket, ansible, molecule, tox, playbook, hacktoberfest
