---
- name: Verify
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: check page
      ansible.builtin.uri:
        url: "http://127.0.0.1:7990"
        status_code: "200"
        timeout: "300"
        return_content: true
      async: "300"
      poll: "10"
      register: result
      until: result.status == 200
      retries: 30

    - name: Check result
      ansible.builtin.fail:
      when: "'bitbucket' not in result.content"
