---
- name: Verify
  hosts: all
  remote_user: root
  become: true
  gather_facts: true
  tasks:
    - name: Check port
      ansible.builtin.wait_for:
        port: 7990
        timeout: 300
        delay: 10
      async: 300
      poll: 10
      register: result
      until: result is succeeded
      retries: 30

    - name: Check page
      ansible.builtin.uri:
        url: http://localhost:7990
        status_code: 200
        timeout: 300
        return_content: true
      async: 300
      poll: 10
      register: result
      until: result.status == 200
      retries: 30
      when: ansible_facts['os_family'] == 'Debian'

    - name: Check result
      ansible.builtin.fail:
      when: "'bitbucket' not in result.content and ansible_facts['os_family'] == 'Debian"
